apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: session-stickyness-http-backend
  labels:
    k8s-app: session-stickyness-http-backend
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: session-stickyness-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: session-stickyness-http-backend
        image: chentao1596/session-stickyness-http-backend:1.0
        ports:
        - containerPort: 9999
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: session-stickyness-http-backend
  namespace: kube-system
  labels:
    k8s-app: session-stickyness-http-backend
spec:
  ports:
  - port: 80
    targetPort: 9999
  selector:
    k8s-app: session-stickyness-http-backend
